language: java
jdk:
  - openjdk11
# Git Push할 Branch
branches:
  only:
    - main

before_script:
  - cd springboot-webService/

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - dldydcns123@gmail.com

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
  access_key_id: $AWS_ACCESS_KEY #Travis repo settings에 설정된 값
  secret_access_key: $AWS_SECRET_KEY
  bucket: freelec-springboot-build-buk #s3 버킷 명
  region: ap-northeast-2
  skip_cleanup: true
  acl: private # zip 파일 접근을 private으로 설정
  local_dir: deploy # before_deploy에서 생성한 디렉토리
  wait-until-deployed: true

